### ISSUE TITLE
Screenrecord fail. Can't open '/sdcard/<filename.mp4'.

### ISSUE THREAD

**Issue by bugre** [muandrew/androidtool-mac#11]
Hi,
First, thanks for the nice tool.
I'm new to Android world so, please be patient.  
I've installed, and taking screenshot's work fine. (so i think i've done correctly the activation of usb debugging).
Trying to screeRECORD, does fail. Always saying that it can't open file `/sdcard/<filename...mp4`

I found a wiki with troubleshooting, and doing it from command line, like:
```bash
09:40 $ /Applications/AndroidTool.app/Contents/Resources/adb shell screenrecord /sdcard/screen.mp4
The max width/height supported by codec is 1920x1088

^C
09:41 $ /Applications/AndroidTool.app/Contents/Resources/adb pull /sdcard/screen.mp4
[100%] /sdcard/screen.mp4
```
does result in a ok capture .mp4 file.

Is there something i could look at the app config that could help find why from the app it doesn't work?

Thanks,

**Comment by muandrew** [comment]
Not sure, what is your phone's OS, manufacture, and model?

**Comment by bugre** [comment]
Hi Andrew,
Thanks for answering, and sorry that i didn't provide the info right away.
phone is:
Brand:UMI 
Model: Max (5.7"screen i think), 
Android: Android 7.0 (this is what's written in 'settings -> about'.

Could it be related with the fact that doing it from shell the phone reports it does support max : 1920x1088 resolution? should it not be 1920x1080?

Thank you
-wm

**Comment by muandrew** [comment]
Don't worry about it. I'll probably ask more questions while I'm trying to pin down your situation. Are you using this out of the box? No configuration changes? What version are you using, or if you built this, which commit did you build off of? I just tested master, and it looks like the video recording is broken, but doesn't look like your particular problem.

Are you familiar with the terminal? If so try calling the screen recording script directly.

In Android Tool under Tools > Terminal Output

What does the terminal output display? When you hit record and stop?
```
$USER/Library/Developer/Xcode/DerivedData/AndroidTool-fjzblxwflhzepddyhavjqyfoerec/Build/Products/Debug/AndroidTool.app/Contents/Resources/startRecordingForSerial.sh
Recording from phone...

$USER/Library/Developer/Xcode/DerivedData/AndroidTool-fjzblxwflhzepddyhavjqyfoerec/Build/Products/Debug/AndroidTool.app/Contents/Resources/postProcessMovieForSerial.sh
###### $USER/Desktop/AndroidTool
copying from phone...
[100%] /sdcard/capture.mp4
/sdcard/capture.mp4: 1 file pulled. 7.0 MB/s (11432 bytes in 0.002s)
cleaning up
Opening file...
```

**Comment by bugre** [comment]
Hi Andrew,
work catching up, sorry for taking so long..
Try to answer..
I did download, unpack and install. In the About dialog it says : "Version 1.68.0 (1)". Didn't do any modification or extra config. After it didn't work at first try, i now normally open the 'terminal/log' window when i test, but i don't think that count's as change.
Yes i'm a terminal fan :) (not so much android one, but pretty familiar with linux, so if i can help.. let's try).

Terminal output, for a screenrecord (that failed) and one screencapture (that worked), is bellow.

```
=================================================
/Users/$USER/Applications/AndroidTool.app/Contents/Resources/startRecordingForSerial.sh
Recording from phone...
The max width/height supported by codec is 1920x1088
1080x1920 is not supported by codec, suggest to set it as 1088x1920

/Users/$USER/Applications/AndroidTool.app/Contents/Resources/postProcessMovieForSerial.sh
###### /Users/$USER/Desktop/AndroidTool
copying from phone...
adb: error: remote object '/sdcard/capture.mp4' does not exist
mv: rename capture.mp4 to UMI_MAXNRD90M$USER05262019074804.mp4: No such file or directory
cleaning up
rm: /sdcard/capture.mp4: No such file or directory
Opening file...
The file /Users/$USER/Desktop/AndroidTool/UMI_MAXNRD90M$USER05262019074804.mp4 does not exist.

/Users/$USER/Applications/AndroidTool.app/Contents/Resources/takeScreenshotOfDeviceWithSerial.sh
###### /Users/$USER/Desktop/AndroidTool
Taking screenshot of DEVICE_ID
...
[100%] /sdcard/launcher3-Launcher-05262019074812.png
/sdcard/launcher3-Launcher-05262019074812.png: 1 file pulled. 29.0 MB/s (390189 bytes in 0.013s)

/Users/$USER/Applications/AndroidTool.app/Contents/Resources/getSerials.sh
DEVICE_ID
=================================================
```



Maybe the problem relies that when i do the manual:
 `AndroidTool.app $ ./Contents/Resources/android-sdk/platform-tools/adb shell screenrecord /sdcard/screen.mp4` 
it also complains about the MAX resolution supported, but does the capture anyway , and the `startRecordingForSerial.sh` does interrupt the process after getting the error/info message?

Bellow is a ffprobe for a short clip captured and pulled directly using `..platform-tools/adb ...` :
As you can see, even with the error/warning message about the supported resolution, the output movie, is still `1088x1920`.

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './screen.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2019-05-26T11:18:32.000000Z
    com.android.version: 7.0
  Duration: 00:00:16.96, start: 0.000000, bitrate: 1597 kb/s
    Stream #0:0(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 1088x1920, 1595 kb/s, SAR 1:1 DAR 17:30, 21.16 fps, 90k tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2019-05-26T11:18:32.000000Z
      handler_name    : VideoHandle
```

Regards,
-wm

**Comment by bugre** [comment]
Hi again, 

As it's Sunday, with kids still sleeping :), i did some more digging, adding `set -xv` to the record script to understand what parameter it was using and indeed if you call the "../adb shell record..." passing resolution argument, and that doesn't match the device's resolution it fails to record.

And for our case the calling parameters are:
```
.../AndroidTool.app/Contents/Resources/android-sdk/platform-tools/adb -s DEVICE_ID shell screenrecord --bit-rate 3025000 --verbose --size 1080x1920 /sdcard/capture.mp4
```
And that result's in failure.

But if i change that to:
```
.../AndroidTool.app/Contents/Resources/android-sdk/platform-tools/adb -s DEVICE_ID shell screenrecord --bit-rate 3025000 --verbose --size 1088x1920 /sdcard/capture.mp4
```
It works like a charm :)

...

I followed digging a little, trying to figure out a way to detect the resolution, and indeed there is a `...adb shell dumpsys display..` , but on all that output i can't find a single place where it says "1088" , all places refer the width as 1080. So i think this device&Android version is somewhat screwed.

Any tip of additional debugging options i could execute to find screen resolutions? 

Thanks
-wm

**Comment by muandrew** [comment]
Hey would you mind testing https://github.com/muandrew/androidtool-mac/releases/tag/release%2F1.69.0 for me? Let me know if it works.

**Comment by bugre** [comment]
Hi Andrew,

Worked like a charm (at least in my scenario). 
Thanks.

-wm

**Comment by muandrew** [comment]
mm, good luck and have fun

**Comment by EvgenyTerebenin** [comment]
Hi! 
Screen recording doesn't works on Honor 10 (Huawei COL-L29), android 9.0, androidtool-mac 1.69.0.

Log output: 

/Applications/AndroidTool.app/Contents/Resources/startRecordingForSerial.sh
Recording from phone...
/system/bin/sh: screenrecord: not found
Trying again, but now without setting the resolution.
/system/bin/sh: screenrecord: not found

/Applications/AndroidTool.app/Contents/Resources/postProcessMovieForSerial.sh
###### /Users/evgenyterebenin/Pictures/AndroidTool
copying from phone...
adb: error: failed to stat remote object '/sdcard/capture.mp4': No such file or directory
mv: rename capture.mp4 to COL-L29RUHUAWEICOL-L29evgenyterebenin09192019104545.mp4: No such file or directory
Generating gif...
ffmpeg version 2.6.1 Copyright (c) 2000-2015 the FFmpeg developers
  built with llvm-gcc 4.2.1 (LLVM build 2336.11.00)
  configuration: --prefix=/Volumes/Ramdisk/sw --enable-gpl --enable-pthreads --enable-version3 --enable-libspeex --enable-libvpx --disable-decoder=libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libgsm --enable-libvidstab --enable-libx265 --disable-doc --arch=x86_64 --enable-runtime-cpudetect
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
COL-L29RUHUAWEICOL-L29evgenyterebenin09192019104545.mp4: No such file or directory
cleaning up
rm: /sdcard/capture.mp4: No such file or directory
Opening file...
The file /Users/evgenyterebenin/Pictures/AndroidTool/COL-L29RUHUAWEICOL-L29evgenyterebenin09192019104545.mp4 does not exist.
![Screenshot_20190919_112317_com finalwire aida64](https://user-images.githubusercontent.com/17678440/65226791-2d535700-dad0-11e9-905a-603ff6555842.jpg)

**Comment by muandrew** [comment]
Hello Evgeny,

Thanks for the report. For now can you try using `screenrecord` without the use of android-tool for me? https://developer.android.com/studio/command-line/adb#screenrecord. Based on the output of the error log it looks like the cli tool is missing from your phone. If so I'll improve the error message and think about other ways of recording the image. By the way I appreciate the detail of your report. (note this seems to be a different error, I'll at the very least add a new error message to avoid opening old tickets)

Thanks,
Andrew

**Comment by muandrew** [comment]
reopening so i dont forget

**Comment by muandrew** [comment]
I'm going to close this issue unless there are further updates. Please open a new issue if there are any problems. Don't forget to update to the latest version and fill out any information you can find (mac os version, device version, etc). I'll get back to you as soon as possible (If I'm reading my emails) and ask for more details if I need them.
