### ISSUE TITLE
Script not running

### ISSUE THREAD

**Issue by prydda** [muandrew/androidtool-mac#5]
Script is stuck on finished, and the log file is 0kb. 
Also when checking in the terminal it's last line is `Application Support/AndroidTool/UserScripts/Take Bugreport.sh: line 21: /Applications/AndroidTool.app/Contents/Resources/adb: No such file or directory`

**Comment by muandrew** [comment]
which version of the app is this?

**Comment by prydda** [comment]
latest! 

grabbed here: 
https://github.com/muandrew/androidtool-mac/releases/

**Comment by muandrew** [comment]
Working on a full solution, but you do a quick fix by the following line to where `adb` is set.
`adb=$ANDROID_SDK_ROOT/platform-tools/adb`
